### PR TITLE
Add Facebook image and name

### PR DESCRIPTION
**Pull request by gmertk**
For this commit I only added an image and a label. Later we can fix it to match with the Sketch design.
I cached the profile picture but maybe it is better if we use a caching library like sdwebimage or hanekeswift? 

Let me know how it looks:)

### CODE REVIEW

**Comment by adrianonco** [comment]
@gmertk, only notice that in the Merge button appears to me a note that say "the Travis CI build failed, merge with caution". I'm not a dev, but I hope this notice will be helpful ;)

And thanks for that commit man!

**Comment by bshyong** [comment]
@gmertk is it possible to downsize the label so that it doesn't get cut off?

screen shot 2015-02-16 at 7 25 50 pm

**Comment by gmertk** [comment]
@bshyong It should be ok now

**Comment by bshyong** [comment]
awesome, thanks @gmertk! I'll award your bounty on Assembly too once I merge this.

**Pull request merged**
