### PR TITLE
Fix facebook login bug.

### PR DESCRIPTION
**Pull request by jPaolantonio**
* Add Facebook-iOS-SDK from cocoapods.
 * Alphabetize Podfile.
 * Sort LoginViewController.swift into extensions.

https://assembly.com/giraff/bounties/191

### CODE REVIEW

**Comment by blcooley** [comment]
I think this is probably OK, but I'm relatively new to the project and noticed the Travis CI build failed on some unrelated code. I'll fetch this PR to test locally later today when I get a chance.

**Comment by adrianonco** [comment]
Thanks so much @blcooley :))

And yes, Travis always said the same. I'm not a dev, so do you know guys know how could we to fix that?

**Comment by blcooley** [comment]
@adrianonco I suspect I can fix it. I'll take a look after this PR.

**Comment by jPaolantonio** [comment]
@blcooley Yes, it looks like the build is failing on master. Let me know if you want me to take a look.

**Comment by blcooley** [comment]
@jPaolantonio Yes, please do. I probably won't be able to get to it for a few hours.

**Comment by jeroenleenarts** [comment]
Last I checked Travis doen't work correctly with Swift 1.2 yet.

Code looks good to me. :+1: Checked it on simulator and device.

**Comment by jeroenleenarts** [comment]
@jPaolantonio Check here to get your coins sorted: https://github.com/asm-products/giraff-ios/pull/28

**Pull request merged**
