### PR TITLE
[iOS] Add Google Analytics to iOS app

### PR DESCRIPTION
**Pull request by fedosov**
https://assembly.com/giraff/bounties/167

### CODE REVIEW

**Comment by bshyong** [comment]
sorry I did see this @fedosov; I'll merge this soon! We need to rebase and remove some things like FLAnimatedImage which we don't use any more.

**Comment by jeroenleenarts** [comment]
Merged it into master. :+1:

**Comment by bshyong** [comment]
Thanks Jeroen!



—

**Comment by jeroenleenarts** [comment]
I've not awarded on assembly yet, cause I am unsure if the number of sign-ups is tracked sufficiently. Also noticed that fave image API appears broken atm. but assumed that was due to the "required rework" on that.

**Comment by bshyong** [comment]
Is the API broken? I changed the auth a little bit to support email login - now you only receive an auth token if you log in correctly.  




If you send a correct auth token you will get a response.  I can try resetting your account if it's not working?  Or you could try a different email.



—

**Comment by jeroenleenarts** [comment]
Perhaps there is no auth token sent. I'll check. What I did was:

- Create a new login with my gmail. (Same as on github)
- Stream screen loaded correctly.
- Fave screen showed no content. Checked server response, empty images array.

**Comment by jeroenleenarts** [comment]
Seems like a temporary hick-up. Getting faves again now. Strange...

Code was correctly posting a auth token. Perhaps there is an edge case when the user is freshly logged in that there is no token available then.

**Comment by jeroenleenarts** [comment]
My bad, was using a new account. (doh!)

**Pull request merged**
