### PR TITLE
Flag image as inappropriate

### PR DESCRIPTION
**Pull request by marcusvmsa**

### CODE REVIEW

**Comment by adrianonco** [comment]
@blcooley I think here is what you were looking for ;)

**Comment by adrianonco** [comment]
@blcooley or @josiasds, let me know please when I can merge so @mamute can still helping in other critical bounties +1:

**Comment by blcooley** [comment]
@adrianonco No sweat, testing now and should be able to merge soon.

**Comment by adrianonco** [comment]
Cool @blcooley!

**Comment by blcooley** [comment]
@adrianonco I think this is OK, and you can merge it (looks like I have rights to merge too if you prefer I handle it).

From a UX standpoint, I'd prefer giving the user a chance to cancel accidental flag presses since we are already showing a modal alert. I'd also change the message, which currently says "Gif reported" to something more descriptive. If you agree with that and @mamute can update the pull request, maybe it makes sense to wait. Otherwise, I can create a new (small) bounty to do the update and follow up after the merge. Whatever is easiest for all is fine with me.

**Comment by mamute** [comment]
@blcooley I fully agree with your thoughts :) 

I can change the message and put a confirm box before report the gif. What message do you guys suggest?

**Comment by blcooley** [comment]
@mamute Here's what I was using for the alert view:

let alert: UIAlertView = UIAlertView(title: "Flag image",
            message: "Are you sure you want to flag this image as offensive?",
            delegate: self,
            cancelButtonTitle: "Cancel",
            otherButtonTitles: "Flag")

Open to other suggestions, though.

**Comment by adrianonco** [comment]
I agree with the @blcooley suggestion @mamute, so you can go with it ;)

Thanks to both!!

**Comment by mamute** [comment]
Done :)

**Comment by blcooley** [comment]
@mamute Perfect; thanks!

**Pull request merged**
